seed: 42
output_dir: data/outputs

model_name: Qwen/Qwen2.5-7B-Instruct-1M
device: cuda

vllm_params:
  gpu_memory_utilization: 0.8
  max_model_len: 1010000
  max_num_batched_tokens: 131072
  enforce_eager: true  

sampling_params:
  temperature: 0.0
  n: 1
  max_tokens: 2048

dataset:
  data_loader: HELMET
  path: data/benchmarks/HELMET
  split: kilt
  name: hotpotqa-dev-multikilt_1000_k1000_dep3
  max_test_samples: 100
  prompt_obj: prompts/inference/HELMET/zero_shot.json

retrieval:
  mode: "full"