seed: 42
output_dir: data/outputs

model_name: Qwen/Qwen2.5-7B-Instruct
device: cuda

vllm_params:
  gpu_memory_utilization: 1.0
  max_model_len: 131072

sampling_params:
  temperature: 0.0
  n: 1
  max_tokens: 2048

dataset:
  data_loader: LongBench-v2
  path: THUDM/LongBench-v2
  split: train
  name: null
  prompt_obj: prompts/inference/LongBench-v2/zero_shot_no_context.json

retrieval:
  mode: "none"